import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Render the root layout for the application.
 *
 * @param {Object} children - The child components to be rendered.
 * @return {JSX.Element} The root layout element.
 */
export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark" data-theme="mytheme">
      <body className={`${inter.className}`}>{children}</body>
    </html>
  );
}
